module.exports = {
  projectDir: "C:/Users/chiar/Desktop/MSW",
  contractsDir: "C:/Users/chiar/Desktop/MSW/contracts",
  testsDir: "C:/Users/chiar/Desktop/MSW/test",
  skipContracts: [""],
  skipTests: [""],
  contractsGlob: "/**/*.sol",
  testsGlob: "/**/*.js",
  resumeDir: "",
  onlySelection: true,
  previousMatrixPath: "",
  currentMatrixPath: "",
  killedSymbol: "  K ",
  aliveSymbol: "  - ",
  unknownSymbol: "  ? ",
  //finalMatrixPath: "",
  //mutationOpConfig: "",
};
