module.exports = {
  projectDir: "C:/Users/franc/Desktop/ABC",
  contractsDir: "C:/Users/franc/Desktop/ABC/contracts",
  testsDir: "C:/Users/franc/Desktop/ABC/test",
  skipContracts: [""],
  skipTests: [""],
  contractsGlob: "/**/*.sol",
  testsGlob: "/**/*.js",
  resumeDir: "",
  previousMatrixPath: "C:/Users/franc/Desktop/CDE_0_log.txt",
  currentMatrixPath: "C:/Users/franc/Desktop/CDE_1_log.txt",
  killedSymbol: "K",
  aliveSymbol: "-",
  unknownSymbol: "?",
  //finalMatrixPath: "",
  // mutationOpConfig: "",
};
