module.exports = {
  projectDir: "../example_projects/CDE",
  contractsDir: "../example_projects/CDE/contracts",
  testsDir: "../example_projects/CDE/test",
  skipContracts: [""],
  skipTests: [""],
  contractsGlob: "/**/*.sol",
  testsGlob: "/**/*.{js,sol}",
  resumeDir: "",
  onlySelection: true,
  previousMatrixPath: "",
  currentMatrixPath: "",
  killedSymbol: "  K ",
  aliveSymbol: "  - ",
  unknownSymbol: "  ? ",
  //finalMatrixPath: "",
  //mutationOpConfig: "",
};
